[package]
name = "clinews"
version = "0.1.0"
edition = "2024"

description="A simple CLI news reader app"
license="MIT"
authors=["Arun Vijay Sampath"]

[dependencies]
newsapi = {path ="./newsapi"}
dotenv = "0.15.0"
crossterm = "0.28.1"
termimad = "0.31.2"
