[package]
name = "clinews"
version = "0.1.0"
edition = "2024"

[dependencies]
color = "0.2.3"
colour = "2.1.0"
serde = {version = "1.0.127", features = ["derive"]}
serde_json = "1.0.66"
ureq = "=2.12.1"
